/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "comyazdzxnsfrwvxnehg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvbXlhemR6eG5zZnJ3dnhuZWhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NTE1OTMsImV4cCI6MjA4NzMyNzU5M30.mH5nWBFQXdoCSU-VNH-vidJnihCowSWVgDzG51uQHjo"